### ISSUE TITLE
[NFR] monitor and recover NTP

### ISSUE THREAD

**Issue by tdely** [MONROE-PROJECT/Watchdog#1]
NTP not initiating correctly is a frequent problem on the MONROE nodes and a big problem for anything relying on time, which has historically resulted in lots of support issues.

It should be simple to implement this by checking if there are only stratum 16 NTP peers, and restarting the service if this is the case. Time otherwise being greatly off should not be a concern in this check as the node config now has been set to not panic on great time skew.

**Comment by relet** [comment]
What the time module currently does is check the offset of `ntpq -pn` and
two repairs if that is >60 - restart ntp service, or run ntpd -gq

Is checking the peers enough/better suited to serve as a symptom? I'm happy
to change it.

**Comment by tdely** [comment]
Checking the peer stratum is probably the best way to see that you are actually connected.

Often all peer connections get stuck at `.INIT.`, and as there is no actual NTP communication to/from the peer no stats are available:

```
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 xxx.xx.xxx.xx   .INIT.          16 u    - 1024    0    0.000    0.000   0.000
 xx.xxx.x.xx     .INIT.          16 u    - 1024    0    0.000    0.000   0.000
 xxxx:xxxx:xxxx: .INIT.          16 u    - 1024    0    0.000    0.000   0.000
 xxx.xxx.xx.xxx  .INIT.          16 u    - 1024    0    0.000    0.000   0.000
```

Which means currently no action is taken when the node is booted up and fails to set up peer association; service is not restarted, `ntpd -gq` is not run.

`ntpd -gq` will no longer be required since tinker panic is disabled in config.

The best site I've found for ntpd documentation is http://nlug.ml1.co.uk/2012/01/ntpq-p-output/831, it covers most things.

**Comment by relet** [comment]
Ok, perfect. I will change that then.
